# Generated by Django 4.0.2 on 2022-02-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='quest_permit',
            new_name='guest_permit',
        ),
    ]
